CREATE DATABASE IF NOT EXISTS lidt;
USE lidt;

CREATE TABLE IF NOT EXISTS Industry (
	IndustryID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS TimeZone (
	TimeZoneID NVARCHAR(32) PRIMARY KEY,
    UTCOffset NVARCHAR(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS USState (
	USStateID NCHAR(2) PRIMARY KEY,
    Name NVARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS Client (
	CreatedDate DATETIME		NOT NULL DEFAULT NOW(),
	ClientID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IndustryID INT UNSIGNED 	NOT NULL REFERENCES Industry(IndustryID),
    Name NVARCHAR(64) 			NOT NULL,
    Address1 NVARCHAR(64)		NOT NULL,
    Address2 NVARCHAR(32),
    City NVARCHAR(64)			NOT NULL,
    State NCHAR(2)				NOT NULL,
    ZipCode NVARCHAR(10)		NOT NULL,
    ContactName NVARCHAR(128)	NOT NULL,
    ContactEmail NVARCHAR(256)	NOT NULL,
    ContactPhone NVARCHAR(10)	NOT NULL,
    TimeZoneID NVARCHAR(32) 	NOT NULL REFERENCES Industry(IndustryID),
    CONSTRAINT UX_Client UNIQUE KEY (Name, ContactName)
);

CREATE TABLE IF NOT EXISTS User (
	CreatedDate DATETIME	NOT NULL DEFAULT NOW(),
	UserID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ClientID INT UNSIGNED REFERENCES Client(ClientID),
    UserName NVARCHAR(32)	NOT NULL,
    FirstName NVARCHAR(64)	NOT NULL,
    LastName NVARCHAR(32)	NOT NULL,
    Email NVARCHAR(256)		NOT NULL,
    HomePhone NVARCHAR(10),
    MobilePhone NVARCHAR(10),
    WorkPhone NVARCHAR(10),
    Ext NVARCHAR(6),
    CONSTRAINT UX_UserName UNIQUE KEY (UserName),
    CONSTRAINT UX_UserEmail UNIQUE KEY (Email)
);

CREATE TABLE IF NOT EXISTS Device (
	CreatedDate DATETIME	NOT NULL DEFAULT NOW(),
    CreatedBy	INT UNSIGNED NOT NULL REFERENCES User(UserID),
	DeviceID NVARCHAR(36) PRIMARY KEY,
    ClientID INT UNSIGNED 	NOT NULL REFERENCES Client(ClientID),
    Name NVARCHAR(64)		NOT NULL,
    MACAddress NVARCHAR(36)	NOT NULL,
    Location NVARCHAR(32),
    CONSTRAINT UX_Device UNIQUE KEY (MACAddress)
);

-- TODO: Need to change EventType to string
CREATE TABLE DeviceEvents (
	DeviceID NVARCHAR(36),
	CreatedDate DATETIME NOT NULL DEFAULT NOW(),
	EventType ENUM('entry', 'exit'),
	PRIMARY KEY(DeviceID, CreatedDate)
);

CREATE TABLE IF NOT EXISTS ClientBusinessHours (
    ClientID INT UNSIGNED 	NOT NULL REFERENCES Client(ClientID),
    DayOfWeek INT			NOT NULL,
    IsOpen BIT				NOT NULL	DEFAULT 0,
    OpenTime TIME(2)		NOT NULL	DEFAULT '00:00:00',
    CloseTime TIME(2)		NOT NULL	DEFAULT '00:00:00',
    UTCOffset NVARCHAR(6)	NOT NULL,
    PRIMARY KEY (ClientID, DayOfWeek)
);
